import {
  FileText,
  AlertTriangle,
  Lightbulb,
  BarChart3,
  Handshake,
  Users,
  Target,
  Atom,
  GraduationCap,
  Cpu,
  HeartHandshake,
  Award,
  Mic,
  Newspaper,
  Globe2,
  MapPin,
  Calendar,
  BookOpen,
  Briefcase,
  Leaf,
  FlaskConical,
  Building2,
  Heart,
  Trophy,
  Tv,
  Play,
  Download,
  Eye,
  CheckCircle2,
  Plane,
  Sparkles,
  Star,
  Rocket,
  Mail,
  Music2,
  Quote,
  PenLine,
  Landmark,
  Compass,
  Puzzle,
  Ear,
  Home,
  Image as ImageIcon,
  type LucideIcon,
} from "lucide-react";

/**
 * A curated, bounded icon set clients can reference by name from content JSON
 * (case-study sections/categories, research interests). Not a wildcard import
 * of all of `lucide-react` — that would defeat tree-shaking and bloat every
 * client bundle with 1000+ unused icon modules.
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  FileText,
  AlertTriangle,
  Lightbulb,
  BarChart3,
  Handshake,
  Users,
  Target,
  Atom,
  GraduationCap,
  Cpu,
  HeartHandshake,
  Award,
  Mic,
  Newspaper,
  Globe2,
  MapPin,
  Calendar,
  BookOpen,
  Briefcase,
  Leaf,
  FlaskConical,
  Building2,
  Heart,
  Trophy,
  Tv,
  Play,
  Download,
  Eye,
  CheckCircle2,
  Plane,
  Sparkles,
  Star,
  Rocket,
  Mail,
  Music2,
  Quote,
  PenLine,
  Landmark,
  Compass,
  Puzzle,
  Ear,
  Home,
  // Registered under the lucide name clients will reach for, aliased on import
  // only because `Image` collides with `next/image` in most files here.
  Image: ImageIcon,
};

/** Resolve a content-configured icon name to a component, or undefined if unset/unknown. */
export function resolveIcon(name?: string): LucideIcon | undefined {
  return name ? ICON_REGISTRY[name] : undefined;
}
