import blurMap from "@/data/image-blur.json";
import sizeMap from "@/data/image-size.json";

/**
 * Blur placeholder for a /public image path, generated by `npm run
 * generate-blur` (see scripts/generate-blur.mjs). Returns undefined for
 * images that script hasn't covered — callers should render without a
 * placeholder rather than fail.
 */
export function getBlurDataURL(src: string): string | undefined {
  return (blurMap as Record<string, string>)[src];
}

export type ImageSize = { w: number; h: number };

/**
 * Intrinsic pixel size for a /public image path, from the same
 * `npm run generate-blur` pass. Composed pages name only a path, so anything
 * that has to lay an image out at its real ratio — the lightbox, a masonry
 * tile — reads it from here. Falls back to 4:3 for a path the script hasn't
 * covered, which keeps a missing entry a cosmetic issue rather than a crash.
 */
export function getImageSize(src: string, fallback: ImageSize = { w: 1200, h: 900 }): ImageSize {
  const found = (sizeMap as Record<string, ImageSize>)[src];
  return found?.w && found?.h ? found : fallback;
}
