/**
 * GENERATED by scripts/gen-module-paths.mjs — do not edit by hand.
 * Regenerate after adding or moving a module's files:
 *     node scripts/gen-module-paths.mjs
 *
 * Maps an engine file to the modules it exists to serve. A file is safe to leave
 * out of a client repo only when EVERY module listed for it is disabled there.
 * See the generator for how ownership is derived and why it is not hand-written.
 */
export const MODULE_PATH_OWNERS: Record<string, readonly string[]> = {
  "src/app/[locale]/[slug]/page.tsx": [
    "pages"
  ],
  "src/app/[locale]/account/layout.tsx": [
    "membership"
  ],
  "src/app/[locale]/account/page.tsx": [
    "membership"
  ],
  "src/app/[locale]/ai/layout.tsx": [
    "ai"
  ],
  "src/app/[locale]/ai/page.tsx": [
    "ai"
  ],
  "src/app/[locale]/biography/layout.tsx": [
    "biography"
  ],
  "src/app/[locale]/biography/page.tsx": [
    "biography"
  ],
  "src/app/[locale]/engagements/layout.tsx": [
    "engagements"
  ],
  "src/app/[locale]/engagements/page.tsx": [
    "engagements"
  ],
  "src/app/[locale]/gallery/layout.tsx": [
    "gallery"
  ],
  "src/app/[locale]/gallery/page.tsx": [
    "gallery"
  ],
  "src/app/[locale]/innovation/[category]/[slug]/page.tsx": [
    "innovation"
  ],
  "src/app/[locale]/innovation/[category]/page.tsx": [
    "innovation"
  ],
  "src/app/[locale]/innovation/layout.tsx": [
    "innovation"
  ],
  "src/app/[locale]/innovation/page.tsx": [
    "innovation"
  ],
  "src/app/[locale]/join/layout.tsx": [
    "membership"
  ],
  "src/app/[locale]/join/page.tsx": [
    "membership"
  ],
  "src/app/[locale]/label/[artist]/ArtistClient.tsx": [
    "label"
  ],
  "src/app/[locale]/label/[artist]/layout.tsx": [
    "label"
  ],
  "src/app/[locale]/label/[artist]/page.tsx": [
    "label"
  ],
  "src/app/[locale]/label/layout.tsx": [
    "label"
  ],
  "src/app/[locale]/label/page.tsx": [
    "label"
  ],
  "src/app/[locale]/links/layout.tsx": [
    "links"
  ],
  "src/app/[locale]/links/page.tsx": [
    "links"
  ],
  "src/app/[locale]/macro-influencer/layout.tsx": [
    "influencer"
  ],
  "src/app/[locale]/macro-influencer/page.tsx": [
    "influencer"
  ],
  "src/app/[locale]/merch/layout.tsx": [
    "merch"
  ],
  "src/app/[locale]/merch/page.tsx": [
    "merch"
  ],
  "src/app/[locale]/music/[slug]/page.tsx": [
    "music"
  ],
  "src/app/[locale]/music/[slug]/ReleaseClient.tsx": [
    "music"
  ],
  "src/app/[locale]/music/layout.tsx": [
    "music"
  ],
  "src/app/[locale]/music/page.tsx": [
    "music"
  ],
  "src/app/[locale]/posts/[slug]/page.tsx": [
    "posts"
  ],
  "src/app/[locale]/posts/layout.tsx": [
    "posts"
  ],
  "src/app/[locale]/posts/page.tsx": [
    "posts"
  ],
  "src/app/[locale]/press/layout.tsx": [
    "press"
  ],
  "src/app/[locale]/press/page.tsx": [
    "press"
  ],
  "src/app/[locale]/research/layout.tsx": [
    "research"
  ],
  "src/app/[locale]/research/page.tsx": [
    "research"
  ],
  "src/app/[locale]/tour/layout.tsx": [
    "tour"
  ],
  "src/app/[locale]/tour/page.tsx": [
    "tour"
  ],
  "src/app/[locale]/vault/layout.tsx": [
    "vault"
  ],
  "src/app/[locale]/vault/page.tsx": [
    "vault"
  ],
  "src/app/admin/(app)/help/page.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/layout.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/media/MediaGrid.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/media/page.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/media/Uploader.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/page.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/pages/[slug]/page.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/pages/page.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/pages/PageEditor.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/posts/[slug]/page.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/posts/new/page.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/posts/page.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/posts/PostEditor.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/settings/page.tsx": [
    "crm"
  ],
  "src/app/admin/(app)/settings/SettingsForm.tsx": [
    "crm"
  ],
  "src/app/admin/AdminShell.tsx": [
    "crm"
  ],
  "src/app/admin/layout.tsx": [
    "crm"
  ],
  "src/app/admin/login/LoginForm.tsx": [
    "crm"
  ],
  "src/app/admin/login/page.tsx": [
    "crm"
  ],
  "src/app/api/account/profile/route.ts": [
    "membership"
  ],
  "src/app/api/admin/login/route.ts": [
    "crm"
  ],
  "src/app/api/admin/logout/route.ts": [
    "crm"
  ],
  "src/app/api/admin/pages/route.ts": [
    "crm"
  ],
  "src/app/api/admin/posts/route.ts": [
    "crm"
  ],
  "src/app/api/admin/settings/route.ts": [
    "crm"
  ],
  "src/app/api/admin/upload/route.ts": [
    "crm"
  ],
  "src/app/api/checkout/route.ts": [
    "membership"
  ],
  "src/app/api/membership/callback/route.ts": [
    "membership"
  ],
  "src/app/api/membership/checkout/route.ts": [
    "membership"
  ],
  "src/app/api/membership/logout/route.ts": [
    "membership"
  ],
  "src/app/api/membership/portal/route.ts": [
    "membership"
  ],
  "src/app/api/membership/session/route.ts": [
    "membership"
  ],
  "src/app/api/orcid-publications/route.ts": [
    "research"
  ],
  "src/app/api/spotify-albums/route.ts": [
    "music"
  ],
  "src/app/api/spotify-artist/[id]/route.ts": [
    "music"
  ],
  "src/app/api/spotify-artists/route.ts": [
    "music"
  ],
  "src/app/api/superfan/route.ts": [
    "vault"
  ],
  "src/components/AccountProfileForm.tsx": [
    "membership"
  ],
  "src/components/CaseStudyLayout.tsx": [
    "innovation"
  ],
  "src/components/HeroConstellation.tsx": [
    "vault"
  ],
  "src/components/InstagramPostCard.tsx": [
    "influencer",
    "music"
  ],
  "src/components/JourneyMap.tsx": [
    "biography"
  ],
  "src/components/label/LabelSocialLinks.tsx": [
    "label"
  ],
  "src/components/Lightbox.tsx": [
    "gallery"
  ],
  "src/components/MasterDetailList.tsx": [
    "engagements"
  ],
  "src/components/MediaKitBuilder.tsx": [
    "biography"
  ],
  "src/components/MediaKitPdf.tsx": [
    "biography"
  ],
  "src/components/MembershipPanel.tsx": [
    "membership",
    "vault"
  ],
  "src/components/PostBody.tsx": [
    "posts"
  ],
  "src/components/SectionDivider.tsx": [
    "ai",
    "influencer",
    "music",
    "press",
    "tour"
  ],
  "src/data/artist.ts": [
    "ai",
    "gallery",
    "influencer",
    "links",
    "music",
    "tour"
  ],
  "src/data/biography.ts": [
    "biography"
  ],
  "src/data/engagements.ts": [
    "biography",
    "engagements"
  ],
  "src/data/gallery.ts": [
    "gallery"
  ],
  "src/data/influencer.ts": [
    "influencer",
    "music"
  ],
  "src/data/innovation.ts": [
    "biography",
    "innovation"
  ],
  "src/data/instagram.ts": [
    "influencer",
    "music"
  ],
  "src/data/merch.ts": [
    "merch"
  ],
  "src/data/press.ts": [
    "press"
  ],
  "src/data/research.ts": [
    "biography",
    "research"
  ],
  "src/data/vault.ts": [
    "vault"
  ],
  "src/lib/crm/media.ts": [
    "crm"
  ],
  "src/lib/engine-version.ts": [
    "crm"
  ],
  "src/lib/mediaKit.ts": [
    "biography"
  ],
  "src/lib/modules.ts": [
    "ai",
    "biography",
    "crm",
    "engagements",
    "gallery",
    "influencer",
    "innovation",
    "label",
    "links",
    "membership",
    "merch",
    "music",
    "pages",
    "posts",
    "press",
    "research",
    "tour",
    "vault"
  ],
  "src/lib/streaming.ts": [
    "music"
  ],
  "src/lib/structured-data-label.ts": [
    "label"
  ],
  "src/lib/structured-data-music.ts": [
    "music"
  ],
  "src/lib/tex.tsx": [
    "research"
  ]
};
